services:
  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./gateway:/gateway
    ports:
      - 8001:8000
    env_file:
      - ./gateway/.env

  auth:
    image: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth:/auth
    ports:
      - 8002:8000
    env_file:
      - ./auth/.env
